-- MySQL Script generated by MySQL Workbench
-- ศ. 15 ม.ค. 2564, 14:36:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema schicher_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `schicher_db` ;

-- -----------------------------------------------------
-- Schema schicher_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `schicher_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `schicher_db` ;

-- -----------------------------------------------------
-- Table `schicher_db`.`addimages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schicher_db`.`addimages` ;

CREATE TABLE IF NOT EXISTS `schicher_db`.`addimages` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `add_inspection_cars_id` INT(8) UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `image_path` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_addimages_add_inspection_cars1`
    FOREIGN KEY (`add_inspection_cars_id`)
    REFERENCES `schicher_db`.`add_inspection_cars` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 117;

CREATE INDEX `fk_addimages_add_inspection_cars1_idx` ON `schicher_db`.`addimages` (`add_inspection_cars_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `schicher_db`.`add_inspection_cars`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schicher_db`.`add_inspection_cars` ;

CREATE TABLE IF NOT EXISTS `schicher_db`.`add_inspection_cars` (
  `id` INT(8) UNSIGNED NOT NULL,
  `schi_id` VARCHAR(20) NULL COMMENT 'schi_id',
  `oldcolor` INT(2) NOT NULL,
  `newcolor` INT(2) NOT NULL,
  `year` YEAR(4) NULL DEFAULT NULL COMMENT 'ปีจองรถ',
  `seat_num` INT(2) NULL DEFAULT NULL COMMENT 'จำนวนที่นั่ง',
  `place` VARCHAR(255) NULL DEFAULT NULL COMMENT 'สถานที่ตรวจรถ',
  `register_type` INT(1) NULL DEFAULT NULL COMMENT '0=รถยนต์ส่วนบุคคล 1=จดทะเบียนในนามบริษัท',
  `carreg_num` VARCHAR(255) NULL DEFAULT NULL COMMENT 'ทะเบียนรถ',
  `mileage` INT(7) NULL DEFAULT NULL COMMENT 'เลขไมล์',
  `date_register` DATE NULL DEFAULT NULL,
  `num_owners` INT(2) NULL DEFAULT NULL COMMENT 'จำนวนเจ้าของรถ',
  `gear_type` INT(1) NULL DEFAULT NULL COMMENT '0=manual 1=auto',
  `engine` INT(2) NULL DEFAULT NULL,
  `vin` VARCHAR(191) NULL DEFAULT NULL,
  `benzine` VARCHAR(191) NULL DEFAULT NULL,
  `diesel` VARCHAR(191) NULL DEFAULT NULL,
  `hybrid` VARCHAR(191) NULL DEFAULT NULL,
  `electric` VARCHAR(191) NULL DEFAULT NULL,
  `lpg` VARCHAR(191) NULL DEFAULT NULL,
  `ngv` VARCHAR(191) NULL DEFAULT NULL,
  `cng` VARCHAR(191) NULL DEFAULT NULL,
  `imported_car` CHAR(1) NOT NULL DEFAULT 0 COMMENT '0=ไม่นำเข้า  1=นำเข้า',
  `carinsurance` CHAR(1) NULL DEFAULT NULL COMMENT '0=ไม่มีประกัน 1=มีประกัน',
  `expinsurance` DATE NULL DEFAULT NULL COMMENT 'วันหมดอายุ',
  `insurance` VARCHAR(191) NULL DEFAULT NULL,
  `tent` VARCHAR(191) NULL DEFAULT NULL COMMENT 'เป็นรถเต็นท์หรือไม่\n0=ไม่ไช่ 1=ไช่',
  `fromtent` INT(20) NULL DEFAULT NULL,
  `price` INT(11) UNSIGNED NULL DEFAULT NULL COMMENT 'ราคารถ',
  `payment` INT(11) NULL DEFAULT NULL COMMENT 'ผ่อนชำระ',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `type_cars_id` INT(10) UNSIGNED NOT NULL,
  `model_cars_id` INT(3) NOT NULL,
  `sub_model_cars_id` INT(4) NOT NULL,
  `brand_cars_id` INT(2) NOT NULL,
  `sale_status` ENUM('0', '1') NULL DEFAULT '0' COMMENT 'สถานะการขายรถ 0=ยังไม่ขาย 1=ขายแล้ว',
  `car_status` ENUM('0', '1') NULL DEFAULT '1' COMMENT '0=ไม่ใช้งาน 1=ใช้งาน',
  `ccs_id` INT(2) NOT NULL,
  `created_by` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `schi_id`),
  CONSTRAINT `fk_oldcolors`
    FOREIGN KEY (`oldcolor`)
    REFERENCES `schicher_db`.`colors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tents`
    FOREIGN KEY (`fromtent`)
    REFERENCES `schicher_db`.`tents` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_newcolor`
    FOREIGN KEY (`newcolor`)
    REFERENCES `schicher_db`.`colors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_add_inspection_cars_type_cars1`
    FOREIGN KEY (`type_cars_id`)
    REFERENCES `schicher_db`.`type_cars` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_add_inspection_cars_model_cars1`
    FOREIGN KEY (`model_cars_id`)
    REFERENCES `schicher_db`.`model_cars` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_add_inspection_cars_sub_model_cars1`
    FOREIGN KEY (`sub_model_cars_id`)
    REFERENCES `schicher_db`.`sub_model_cars` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_add_inspection_cars_brand_cars1`
    FOREIGN KEY (`brand_cars_id`)
    REFERENCES `schicher_db`.`brand_cars` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_add_inspection_cars_ccs1`
    FOREIGN KEY (`ccs_id`)
    REFERENCES `schicher_db`.`ccs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_add_inspection_cars_users1`
    FOREIGN KEY (`created_by`)
    REFERENCES `schicher_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_colors_idx` ON `schicher_db`.`add_inspection_cars` (`oldcolor` ASC) VISIBLE;

CREATE INDEX `fk_tents_idx` ON `schicher_db`.`add_inspection_cars` (`fromtent` ASC) VISIBLE;

CREATE INDEX `fk_newcolor_idx` ON `schicher_db`.`add_inspection_cars` (`newcolor` ASC) VISIBLE;

CREATE INDEX `fk_add_inspection_cars_type_cars1_idx` ON `schicher_db`.`add_inspection_cars` (`type_cars_id` ASC) VISIBLE;

CREATE INDEX `fk_add_inspection_cars_model_cars1_idx` ON `schicher_db`.`add_inspection_cars` (`model_cars_id` ASC) VISIBLE;

CREATE INDEX `fk_add_inspection_cars_sub_model_cars1_idx` ON `schicher_db`.`add_inspection_cars` (`sub_model_cars_id` ASC) VISIBLE;

CREATE INDEX `fk_add_inspection_cars_brand_cars1_idx` ON `schicher_db`.`add_inspection_cars` (`brand_cars_id` ASC) VISIBLE;

CREATE INDEX `fk_add_inspection_cars_ccs1_idx` ON `schicher_db`.`add_inspection_cars` (`ccs_id` ASC) VISIBLE;

CREATE INDEX `fk_add_inspection_cars_users1_idx` ON `schicher_db`.`add_inspection_cars` (`created_by` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `schicher_db`.`add_inspection_dates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schicher_db`.`add_inspection_dates` ;

CREATE TABLE IF NOT EXISTS `schicher_db`.`add_inspection_dates` (
  `id` INT(8) UNSIGNED NOT NULL,
  `inspector` BIGINT(20) NULL DEFAULT NULL COMMENT 'ช่างผู้ตรวจรถ',
  `inspection_date` DATETIME NULL DEFAULT NULL,
  `remark` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `add_inspection_cars_id` INT(8) UNSIGNED NOT NULL,
  `admin_approve` ENUM('0', '1', '2') NOT NULL DEFAULT '0' COMMENT '0= รอตรวจสอบ 1=ผ่านการตรวจสอบ 2=ไม่ผ่าน',
  `tech_approve` ENUM('0', '1', '2') NOT NULL DEFAULT '0' COMMENT '0= รอตรวจสอบ 1=ผ่านการตรวจสอบ 2=ไม่ผ่าน',
  `confirm_by_admin` BIGINT(20) NULL COMMENT 'ยืนยันโดย',
  `confirm_by_tech` BIGINT(20) NULL,
  `inspection_type_id` BIGINT(20) NOT NULL,
  `packages_id` INT(2) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_technicians`
    FOREIGN KEY (`inspector`)
    REFERENCES `schicher_db`.`technicians` (`id_tech`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_add_inspection_dates_add_inspection_cars1`
    FOREIGN KEY (`add_inspection_cars_id`)
    REFERENCES `schicher_db`.`add_inspection_cars` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_add_inspection_dates_inspection_type1`
    FOREIGN KEY (`inspection_type_id`)
    REFERENCES `schicher_db`.`inspection_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_add_inspection_dates_packages1`
    FOREIGN KEY (`packages_id`)
    REFERENCES `schicher_db`.`packages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'รายการนัดตรวจรถ';

CREATE INDEX `fk_technicians_idx` ON `schicher_db`.`add_inspection_dates` (`inspector` ASC) VISIBLE;

CREATE INDEX `fk_add_inspection_dates_add_inspection_cars1_idx` ON `schicher_db`.`add_inspection_dates` (`add_inspection_cars_id` ASC) VISIBLE;

CREATE INDEX `fk_add_inspection_dates_inspection_type1_idx` ON `schicher_db`.`add_inspection_dates` (`inspection_type_id` ASC) VISIBLE;

CREATE INDEX `fk_add_inspection_dates_packages1_idx` ON `schicher_db`.`add_inspection_dates` (`packages_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `schicher_db`.`add_inspection_owners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schicher_db`.`add_inspection_owners` ;

CREATE TABLE IF NOT EXISTS `schicher_db`.`add_inspection_owners` (
  `id` INT(8) UNSIGNED NOT NULL,
  `nametitle` VARCHAR(191) NULL DEFAULT NULL,
  `firstname` VARCHAR(191) NULL DEFAULT NULL,
  `lastname` VARCHAR(191) NULL DEFAULT NULL,
  `address` VARCHAR(191) NULL DEFAULT NULL,
  `province` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `district` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `subdistrict` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `postalcode` VARCHAR(191) NULL DEFAULT NULL,
  `idcard` VARCHAR(191) NULL DEFAULT NULL,
  `tel` VARCHAR(191) NULL DEFAULT NULL,
  `customertype` VARCHAR(191) NULL DEFAULT NULL,
  `contact` VARCHAR(60) NOT NULL,
  `tel_contact` CHAR(10) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `add_inspection_cars_id` INT(8) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_provinces`
    FOREIGN KEY (`province`)
    REFERENCES `schicher_db`.`provinces` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_districts`
    FOREIGN KEY (`district`)
    REFERENCES `schicher_db`.`districts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_amphures`
    FOREIGN KEY (`subdistrict`)
    REFERENCES `schicher_db`.`amphures` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_add_inspection_custos_add_inspection_cars1`
    FOREIGN KEY (`add_inspection_cars_id`)
    REFERENCES `schicher_db`.`add_inspection_cars` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_provinces_idx` ON `schicher_db`.`add_inspection_owners` (`province` ASC) VISIBLE;

CREATE INDEX `fk_districts_idx` ON `schicher_db`.`add_inspection_owners` (`district` ASC) VISIBLE;

CREATE INDEX `fk_amphures_idx` ON `schicher_db`.`add_inspection_owners` (`subdistrict` ASC) VISIBLE;

CREATE INDEX `fk_add_inspection_custos_add_inspection_cars1_idx` ON `schicher_db`.`add_inspection_owners` (`add_inspection_cars_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `schicher_db`.`amphures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schicher_db`.`amphures` ;

CREATE TABLE IF NOT EXISTS `schicher_db`.`amphures` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(191) NULL DEFAULT NULL,
  `name_th` VARCHAR(191) NULL DEFAULT NULL,
  `name_en` VARCHAR(191) NULL DEFAULT NULL,
  `province_id` VARCHAR(191) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1007;


-- -----------------------------------------------------
-- Table `schicher_db`.`appointments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schicher_db`.`appointments` ;

CREATE TABLE IF NOT EXISTS `schicher_db`.`appointments` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schicher_db`.`brand_cars`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schicher_db`.`brand_cars` ;

CREATE TABLE IF NOT EXISTS `schicher_db`.`brand_cars` (
  `id` INT(2) NOT NULL,
  `name_brand` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schicher_db`.`ccs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schicher_db`.`ccs` ;

CREATE TABLE IF NOT EXISTS `schicher_db`.`ccs` (
  `id` INT(2) NOT NULL,
  `cc` DECIMAL(2,1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schicher_db`.`colors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schicher_db`.`colors` ;

CREATE TABLE IF NOT EXISTS `schicher_db`.`colors` (
  `id` INT(2) NOT NULL,
  `car_color` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schicher_db`.`details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schicher_db`.`details` ;

CREATE TABLE IF NOT EXISTS `schicher_db`.`details` (
  `id_detail` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `id_car` INT(8) UNSIGNED NOT NULL,
  `carrs01` CHAR(1) NOT NULL,
  `carrs02` CHAR(1) NOT NULL,
  `carrs03` CHAR(1) NOT NULL,
  `carrs04` CHAR(1) NOT NULL,
  `carrs05` CHAR(1) NOT NULL,
  `carrs06` CHAR(1) NOT NULL,
  `carrs07` CHAR(1) NOT NULL,
  `carrs08` CHAR(1) NOT NULL,
  `carrs09` CHAR(1) NOT NULL,
  `carrs10` CHAR(1) NOT NULL,
  `carrs11` CHAR(1) NOT NULL,
  `carrs12` CHAR(1) NOT NULL,
  `carin01` CHAR(1) NOT NULL,
  `carin02` CHAR(1) NOT NULL,
  `carin03` CHAR(1) NOT NULL,
  `carin04` CHAR(1) NOT NULL,
  `carin05` CHAR(1) NOT NULL,
  `carin06` CHAR(1) NOT NULL,
  `carin07` CHAR(1) NOT NULL,
  `carin08` CHAR(1) NOT NULL,
  `exterior_01` CHAR(2) NOT NULL,
  `exterior_02` CHAR(2) NOT NULL,
  `exterior_03` CHAR(2) NOT NULL,
  `exterior_04` CHAR(2) NOT NULL,
  `exterior_05` CHAR(2) NOT NULL,
  `exterior_06` CHAR(2) NOT NULL,
  `exterior_07` CHAR(2) NOT NULL,
  `exterior_08` CHAR(2) NOT NULL,
  `exterior_09` CHAR(2) NOT NULL,
  `exterior_10` CHAR(2) NOT NULL,
  `exterior_11` CHAR(2) NOT NULL,
  `exterior_12` CHAR(2) NOT NULL,
  `exterior_13` CHAR(2) NOT NULL,
  `exterior_14` CHAR(2) NOT NULL,
  `exterior_15` CHAR(2) NOT NULL,
  `exterior_16` CHAR(2) NOT NULL,
  `exterior_17` CHAR(2) NOT NULL,
  `exterior_18` CHAR(2) NOT NULL,
  `exterior_19` CHAR(2) NOT NULL,
  `exterior_20` CHAR(2) NOT NULL,
  `interior_01` VARCHAR(3) NOT NULL,
  `interior_02` VARCHAR(3) NOT NULL,
  `interior_03` VARCHAR(3) NOT NULL,
  `interior_04` VARCHAR(3) NOT NULL,
  `interior_05` VARCHAR(3) NOT NULL,
  `interior_06` VARCHAR(3) NOT NULL,
  `interior_07` VARCHAR(3) NOT NULL,
  `interior_08` VARCHAR(3) NOT NULL,
  `interior_09` VARCHAR(3) NOT NULL,
  `interior_10` VARCHAR(3) NOT NULL,
  `interior_11` VARCHAR(3) NOT NULL,
  `interior_12` VARCHAR(3) NOT NULL,
  `interior_13` VARCHAR(3) NOT NULL,
  `interior_14` VARCHAR(3) NOT NULL,
  `interior_15` VARCHAR(3) NOT NULL,
  `chasis_01` CHAR(2) NOT NULL,
  `chasis_02` CHAR(2) NOT NULL,
  `chasis_03` CHAR(2) NOT NULL,
  `comment` TEXT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `add_inspection_dates_id` INT(8) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_detail`),
  CONSTRAINT `fk_add_inspection_car`
    FOREIGN KEY (`id_car`)
    REFERENCES `schicher_db`.`add_inspection_cars` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_details_add_inspection_dates1`
    FOREIGN KEY (`add_inspection_dates_id`)
    REFERENCES `schicher_db`.`add_inspection_dates` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 44;

CREATE INDEX `fk_add_inspection_car_idx` ON `schicher_db`.`details` (`id_car` ASC) VISIBLE;

CREATE INDEX `fk_details_add_inspection_dates1_idx` ON `schicher_db`.`details` (`add_inspection_dates_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `schicher_db`.`districts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schicher_db`.`districts` ;

CREATE TABLE IF NOT EXISTS `schicher_db`.`districts` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `zip_code` VARCHAR(191) NULL DEFAULT NULL,
  `name_th` VARCHAR(191) NULL DEFAULT NULL,
  `name_en` VARCHAR(191) NULL DEFAULT NULL,
  `amphure_id` VARCHAR(191) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 961304;


-- -----------------------------------------------------
-- Table `schicher_db`.`edits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schicher_db`.`edits` ;

CREATE TABLE IF NOT EXISTS `schicher_db`.`edits` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schicher_db`.`events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schicher_db`.`events` ;

CREATE TABLE IF NOT EXISTS `schicher_db`.`events` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `start` DATETIME NOT NULL,
  `end` DATETIME NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schicher_db`.`failed_jobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schicher_db`.`failed_jobs` ;

CREATE TABLE IF NOT EXISTS `schicher_db`.`failed_jobs` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `connection` TEXT NOT NULL,
  `queue` TEXT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `exception` LONGTEXT NOT NULL,
  `failed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schicher_db`.`geographies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schicher_db`.`geographies` ;

CREATE TABLE IF NOT EXISTS `schicher_db`.`geographies` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(255) NOT NULL)
ENGINE = MyISAM
COMMENT = 'InnoDB free: 8192 kB';


-- -----------------------------------------------------
-- Table `schicher_db`.`image_cars_ins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schicher_db`.`image_cars_ins` ;

CREATE TABLE IF NOT EXISTS `schicher_db`.`image_cars_ins` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `im_0` VARCHAR(50) NOT NULL,
  `im_1` VARCHAR(50) NOT NULL,
  `im_2` VARCHAR(50) NOT NULL,
  `im_3` VARCHAR(50) NOT NULL,
  `im_4` VARCHAR(50) NOT NULL,
  `im_5` VARCHAR(50) NOT NULL,
  `im_6` VARCHAR(50) NOT NULL,
  `im_7` VARCHAR(50) NOT NULL,
  `im_A` VARCHAR(50) NOT NULL,
  `im_B` VARCHAR(50) NOT NULL,
  `im_C` VARCHAR(50) NOT NULL,
  `im_D` VARCHAR(50) NOT NULL,
  `im_V` VARCHAR(252) NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  `tents_id` INT(20) NOT NULL,
  `add_inspection_dates_id` INT(8) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_im_puks_tents1`
    FOREIGN KEY (`tents_id`)
    REFERENCES `schicher_db`.`tents` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_image_cars_ins_add_inspection_dates1`
    FOREIGN KEY (`add_inspection_dates_id`)
    REFERENCES `schicher_db`.`add_inspection_dates` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 25
COMMENT = 'im_punk เก็บรูปการตรวจรถแต่ละส่วน';

CREATE INDEX `fk_im_puks_tents1_idx` ON `schicher_db`.`image_cars_ins` (`tents_id` ASC) VISIBLE;

CREATE INDEX `fk_image_cars_ins_add_inspection_dates1_idx` ON `schicher_db`.`image_cars_ins` (`add_inspection_dates_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `schicher_db`.`image_fire_floods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schicher_db`.`image_fire_floods` ;

CREATE TABLE IF NOT EXISTS `schicher_db`.`image_fire_floods` (
  `id_imf` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_car` INT(8) UNSIGNED NULL DEFAULT NULL,
  `confirm_tech` BIGINT(20) NOT NULL,
  `im_fire1` VARCHAR(50) NULL DEFAULT NULL,
  `im_fire2` VARCHAR(50) NULL DEFAULT NULL,
  `im_flood1` VARCHAR(50) NULL DEFAULT NULL,
  `im_flood2` VARCHAR(50) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `tents_id` INT(20) NOT NULL,
  PRIMARY KEY (`id_imf`),
  CONSTRAINT `fk_add_inspection_cars`
    FOREIGN KEY (`id_car`)
    REFERENCES `schicher_db`.`add_inspection_cars` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_image_fire_floods_technicians1`
    FOREIGN KEY (`confirm_tech`)
    REFERENCES `schicher_db`.`technicians` (`id_tech`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_image_fire_floods_tents1`
    FOREIGN KEY (`tents_id`)
    REFERENCES `schicher_db`.`tents` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 21
COMMENT = 'รถน้ำถ้วมไฟใหม้';

CREATE INDEX `fk_add_inspection_cars_idx` ON `schicher_db`.`image_fire_floods` (`id_car` ASC) VISIBLE;

CREATE INDEX `fk_image_fire_floods_technicians1_idx` ON `schicher_db`.`image_fire_floods` (`confirm_tech` ASC) VISIBLE;

CREATE INDEX `fk_image_fire_floods_tents1_idx` ON `schicher_db`.`image_fire_floods` (`tents_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `schicher_db`.`images_mns`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schicher_db`.`images_mns` ;

CREATE TABLE IF NOT EXISTS `schicher_db`.`images_mns` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name_image` VARCHAR(250) NOT NULL,
  `type_image` CHAR(1) NOT NULL,
  `status` CHAR(1) NOT NULL COMMENT '0=ไม่ใช้งาน 1=ใช้งาน',
  `confirm` VARCHAR(40) NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  `add_inspection_cars_id` INT(8) UNSIGNED NOT NULL,
  `tents_id` INT(20) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_images_mns_add_inspection_cars1`
    FOREIGN KEY (`add_inspection_cars_id`)
    REFERENCES `schicher_db`.`add_inspection_cars` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_images_mns_tents1`
    FOREIGN KEY (`tents_id`)
    REFERENCES `schicher_db`.`tents` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 351
COMMENT = 'เก็บรูป การตรวจรถ ในแต่ละส่วน';

CREATE INDEX `fk_images_mns_add_inspection_cars1_idx` ON `schicher_db`.`images_mns` (`add_inspection_cars_id` ASC) VISIBLE;

CREATE INDEX `fk_images_mns_tents1_idx` ON `schicher_db`.`images_mns` (`tents_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `schicher_db`.`inspection_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schicher_db`.`inspection_type` ;

CREATE TABLE IF NOT EXISTS `schicher_db`.`inspection_type` (
  `id` BIGINT(20) NOT NULL,
  `type_name` VARCHAR(45) NULL,
  `type_status` ENUM('0', '1') NULL DEFAULT '1' COMMENT '0=ไม่ใช้งาน 1=ใช้งาน',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schicher_db`.`menus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schicher_db`.`menus` ;

CREATE TABLE IF NOT EXISTS `schicher_db`.`menus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sub_menu_id` INT NULL DEFAULT 0 COMMENT 'Sub  ของเมนู 0=เมนูหลัก',
  `menu_name` VARCHAR(255) NULL COMMENT '\'ชื่อเมนู\'',
  `menu_path` VARCHAR(255) NULL,
  `status` ENUM('0', '1') NULL DEFAULT '1' COMMENT 'สถาณะ 0= ไม่ใช้งาน 1=ใช้งาน',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'menu';


-- -----------------------------------------------------
-- Table `schicher_db`.`migrations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schicher_db`.`migrations` ;

CREATE TABLE IF NOT EXISTS `schicher_db`.`migrations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(191) NOT NULL,
  `batch` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 28;


-- -----------------------------------------------------
-- Table `schicher_db`.`model_cars`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schicher_db`.`model_cars` ;

CREATE TABLE IF NOT EXISTS `schicher_db`.`model_cars` (
  `id` INT(3) NOT NULL,
  `model_name` VARCHAR(255) NOT NULL,
  `brand_cars_id` INT(2) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_model_cars_brand_cars1`
    FOREIGN KEY (`brand_cars_id`)
    REFERENCES `schicher_db`.`brand_cars` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'รุ่นรถ';

CREATE INDEX `fk_model_cars_brand_cars1_idx` ON `schicher_db`.`model_cars` (`brand_cars_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `schicher_db`.`packages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schicher_db`.`packages` ;

CREATE TABLE IF NOT EXISTS `schicher_db`.`packages` (
  `id` INT(2) NOT NULL,
  `package_name` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schicher_db`.`password_resets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schicher_db`.`password_resets` ;

CREATE TABLE IF NOT EXISTS `schicher_db`.`password_resets` (
  `email` VARCHAR(191) NOT NULL,
  `token` VARCHAR(191) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL)
ENGINE = InnoDB;

CREATE INDEX `password_resets_email_index` ON `schicher_db`.`password_resets` (`email` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `schicher_db`.`provinces`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schicher_db`.`provinces` ;

CREATE TABLE IF NOT EXISTS `schicher_db`.`provinces` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(191) NULL DEFAULT NULL,
  `name_th` VARCHAR(191) NULL DEFAULT NULL,
  `name_en` VARCHAR(191) NULL DEFAULT NULL,
  `geography_id` VARCHAR(191) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 78;


-- -----------------------------------------------------
-- Table `schicher_db`.`reports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schicher_db`.`reports` ;

CREATE TABLE IF NOT EXISTS `schicher_db`.`reports` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schicher_db`.`services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schicher_db`.`services` ;

CREATE TABLE IF NOT EXISTS `schicher_db`.`services` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schicher_db`.`sub_model_cars`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schicher_db`.`sub_model_cars` ;

CREATE TABLE IF NOT EXISTS `schicher_db`.`sub_model_cars` (
  `id` INT(4) NOT NULL,
  `sub_model_name` VARCHAR(255) NOT NULL,
  `models_id` INT(3) NOT NULL,
  `brand_cars_id` INT(2) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_sub_models_models1`
    FOREIGN KEY (`models_id`)
    REFERENCES `schicher_db`.`model_cars` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sub_model_cars_brand_cars1`
    FOREIGN KEY (`brand_cars_id`)
    REFERENCES `schicher_db`.`brand_cars` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'รุ่นย่อย';

CREATE INDEX `fk_sub_models_models1_idx` ON `schicher_db`.`sub_model_cars` (`models_id` ASC) VISIBLE;

CREATE INDEX `fk_sub_model_cars_brand_cars1_idx` ON `schicher_db`.`sub_model_cars` (`brand_cars_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `schicher_db`.`technicians`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schicher_db`.`technicians` ;

CREATE TABLE IF NOT EXISTS `schicher_db`.`technicians` (
  `id_tech` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name_tech` VARCHAR(100) NOT NULL,
  `updated_at` VARCHAR(191) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id_tech`))
ENGINE = InnoDB
AUTO_INCREMENT = 4;


-- -----------------------------------------------------
-- Table `schicher_db`.`tents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schicher_db`.`tents` ;

CREATE TABLE IF NOT EXISTS `schicher_db`.`tents` (
  `id` INT(20) NOT NULL AUTO_INCREMENT,
  `id_tax` VARCHAR(13) NOT NULL COMMENT 'เลขที่เสียภาษี',
  `company_name` VARCHAR(255) NOT NULL,
  `tent_name` VARCHAR(255) NULL,
  `address` VARCHAR(255) NOT NULL,
  `map` TEXT NOT NULL,
  `tel_main` VARCHAR(255) NOT NULL,
  `tel_more` VARCHAR(255) NOT NULL,
  `contract_main` VARCHAR(255) NOT NULL,
  `contract_more` VARCHAR(255) NOT NULL,
  `tent_status` ENUM('1', '0') NOT NULL COMMENT '0=ไม่เปิดใช้งาน 1=ใช้งาน',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `provinces_id` BIGINT(20) UNSIGNED NOT NULL,
  `districts_id` BIGINT(20) UNSIGNED NOT NULL,
  `amphures_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tents_provinces1`
    FOREIGN KEY (`provinces_id`)
    REFERENCES `schicher_db`.`provinces` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tents_districts1`
    FOREIGN KEY (`districts_id`)
    REFERENCES `schicher_db`.`districts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tents_amphures1`
    FOREIGN KEY (`amphures_id`)
    REFERENCES `schicher_db`.`amphures` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 21;

CREATE INDEX `fk_tents_provinces1_idx` ON `schicher_db`.`tents` (`provinces_id` ASC) VISIBLE;

CREATE INDEX `fk_tents_districts1_idx` ON `schicher_db`.`tents` (`districts_id` ASC) VISIBLE;

CREATE INDEX `fk_tents_amphures1_idx` ON `schicher_db`.`tents` (`amphures_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `schicher_db`.`type_cars`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schicher_db`.`type_cars` ;

CREATE TABLE IF NOT EXISTS `schicher_db`.`type_cars` (
  `id` INT(10) UNSIGNED NOT NULL,
  `type_car_name` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10;


-- -----------------------------------------------------
-- Table `schicher_db`.`user_binds`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schicher_db`.`user_binds` ;

CREATE TABLE IF NOT EXISTS `schicher_db`.`user_binds` (
  `id` INT NOT NULL,
  `users_id` BIGINT(20) UNSIGNED NOT NULL,
  `tents_id` INT(20) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_binds_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `schicher_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_binds_tents1`
    FOREIGN KEY (`tents_id`)
    REFERENCES `schicher_db`.`tents` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'user ที่ผูกกับ Tent';

CREATE INDEX `fk_user_binds_users1_idx` ON `schicher_db`.`user_binds` (`users_id` ASC) VISIBLE;

CREATE INDEX `fk_user_binds_tents1_idx` ON `schicher_db`.`user_binds` (`tents_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `schicher_db`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schicher_db`.`users` ;

CREATE TABLE IF NOT EXISTS `schicher_db`.`users` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `tel` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `status` ENUM('0', '1') NULL DEFAULT '1' COMMENT '0=ไม่ใช้งาน 1=ใช้งาน',
  `user_type_id` INT(5) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_users_user_type1`
    FOREIGN KEY (`user_type_id`)
    REFERENCES `schicher_db`.`user_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1;

CREATE UNIQUE INDEX `username_UNIQUE` ON `schicher_db`.`users` (`username` ASC) VISIBLE;

CREATE INDEX `fk_users_user_type1_idx` ON `schicher_db`.`users` (`user_type_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `schicher_db`.`user_type_permisions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schicher_db`.`user_type_permisions` ;

CREATE TABLE IF NOT EXISTS `schicher_db`.`user_type_permisions` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `user_type_id` INT(5) NOT NULL,
  `menu_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_type_permision_user_type1`
    FOREIGN KEY (`user_type_id`)
    REFERENCES `schicher_db`.`user_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_type_permision_menu1`
    FOREIGN KEY (`menu_id`)
    REFERENCES `schicher_db`.`menus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'สิทธิ์การเข้าถึง';

CREATE INDEX `fk_user_type_permision_user_type1_idx` ON `schicher_db`.`user_type_permisions` (`user_type_id` ASC) VISIBLE;

CREATE INDEX `fk_user_type_permision_menu1_idx` ON `schicher_db`.`user_type_permisions` (`menu_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `schicher_db`.`user_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schicher_db`.`user_types` ;

CREATE TABLE IF NOT EXISTS `schicher_db`.`user_types` (
  `id` INT(5) NOT NULL,
  `name_type` VARCHAR(255) NOT NULL,
  `status` ENUM('0', '1') NULL DEFAULT '1' COMMENT '0=ไม่ใช้งาน 1=ใช้งาน',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
